# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Noah Reid
tagline:          keep subheading?
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Noah Reid
  url:            https://twitter.com/NM_Reid
  email:          noah.reid@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/nreid/nreid.github.io


pages_list:       {'About':'/about','Archive':'/archive'}
