# Permalinks
permalink:        pretty


# Setup
title:            Noah Reid
tagline:          
url:              http://getpoole.com
paginate:         3
paginate_path:    "page:num"
plugins:          [jekyll-paginate, jekyll-gist]


baseurl:          
author:
  name:           Noah Reid
  url:            https://twitter.com/NM_Reid
  email:          noah.reid@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/nreid/nreid.github.io


pages_list:	{'About':'/about/','Research':'/research/','Publications':'/publications/','Software':'/software/','Archive':'/archive'}
